name: CI Hello Calendar

on:
  push:
    branches:
      - feature/calendar
  pull_request:
    branches:
      - feature/calendar

jobs:
  hello-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Say Hello
        run: |
          echo "Hello from CI ðŸ‘‹"
          echo "Branch: calendar"
          echo "Workflow CI is running successfully"
