name: Mon Premier Workflow
on: [push]

jobs:
  dire-bonjour:
    runs-on: ubuntu-latest
    steps:
      - name: Dire coucou
        run: echo "Hello ! Je suis le robot GitHub et je vois que tu as push√© du code !"